### ISSUE TITLE
No module named 'ipfshttpclient'

### ISSUE THREAD

**Issue by zicmama** [desiredState/IPFSStreamingVideo#2]
python3 src/cli.py --help
```
Traceback (most recent call last):
  File "src/cli.py", line 5, in <module>
    from IPFSStreamingVideo.ipfs_streaming_video import IPFSStreamingVideo
  File "/home/fred/workspace/IPFSStreamingVideo/src/IPFSStreamingVideo/ipfs_streaming_video.py", line 5, in <module>
    import ipfshttpclient
ModuleNotFoundError: No module named 'ipfshttpclient'
```

**Comment by zicmama** [comment]
pip install ipfshttpclient
